### ISSUE TITLE
Covers not showing over Android Auto library 

### ISSUE THREAD

**Issue by felipemldias** [PaulWoitaschek/Voice#1593]
### Overview

Hi there! Thank you for the great app!

One thing I noted is that audiobook covers somehow show up on the Android Auto player, but not on its libraries. Here are some pics depicting the issue:

![Screenshot_20221106-200611](https://user-images.githubusercontent.com/63819261/200200470-7cdf8438-90ae-41b4-90ac-a653effcd11d.png)
![Screenshot_20221106-200552](https://user-images.githubusercontent.com/63819261/200200471-a5a84161-fa0b-424e-ad33-49df20a1746e.png)
![Screenshot_20221106-200626](https://user-images.githubusercontent.com/63819261/200200474-78f55a1d-fafa-4ec4-9f2f-91b7a103e39b.png)
![Screenshot_20221106-200548](https://user-images.githubusercontent.com/63819261/200200475-3ad01c4d-4d68-4aa4-9b8c-c7288ac073c8.png)

It's a minor detail, just letting you know (:

Thanks once again for the great app 🙏

### How to reproduce

1. Open Android Auto
2. Select Voice as audio player 
3. Open libraries 

### Version

6.4.1

### Android Version

33

### Device Model

Pixel 4a (5G)

**Comment by PaulWoitaschek** [comment]
Thanks for the report. This should be fixed in the latest versions.

**Comment by felipemldias** [comment]
Thank you for your attention to this issue! I'm afraid I'm still experiencing it on version 7.0.12, which I updated from Github just in case. I'm on android 13 and on Maps 11.77 versions.
