### ISSUE TITLE
Books appearing twice as exact duplicates

### ISSUE THREAD

**Issue by dbr** [PaulWoitaschek/Voice#968]
I have some Audible books split into per-chapter mp3's in Voice (using [audible_split](https://github.com/LukasKnuth/audible_split)).

These work and play perfectly, only problem is: each book appears twice in the main listing. They appear identical (same title, same runtime, same chapters within each) and I can play either one without issue

I can't work out how to debug this any further - any suggestions or additional details I can provide? So far I have checked:

- The metadata appears to be consistent between each file - only "title" and "track" vary with each, and the first chapter has the cover art embedded.
- I only have one folder in the "Audiobooks folders" setting.
- If I remove the files, they indeed disappear (I am syncing the files with Resillio Sync and thought maybe it's "archive deleted file" was causing confusion, but nope)

Version details:

App-Version: 5.0.1
Phone Name: Samsung Galaxy S8
Android Version: 9

**Comment by dbr** [comment]
(#934 would potentially help somewhat in this situation - e.g if I long-press on a title it shows the "Name/Cover from internet/etc", would be helpful if there was an additional "Show file info" option)

**Comment by bjohas** [comment]
I have a potentially similar situation, with a folder structure
```
audio books / 
audio books / book title / 
audio books / book title / track1.mp3
audio books / book title / track2.mp3
```

There are also two entries. One seems to use the folder name, the other seems to be based on metadata.

**Comment by bjohas** [comment]
Amendment: I uninstall / reinstalled the app, and the listing is now fixed. Maybe the books were scanned twice, or it happened at a version change?

**Comment by dbr** [comment]
Reinstalling worked around the problem for me also (was still happening the recently released 1.8.1 Play Store version)

I did add and remove the same location in the "Audiobook location" setting a few times, trying to work out why some books weren't appearing (which turned out to be bad MP3 metadata). They were removed from the UI but maybe the setting got "stuck" somehow - this would explain why even newly added files appeared twice

**Comment by PaulWoitaschek** [comment]
I believe this is fixed in later versions of Voice.
