### ISSUE TITLE
playback starts on remove sleep timer

### ISSUE THREAD

**Issue by clausmuus** [PaulWoitaschek/Voice#987]
The Playback should not start if I remove the sleep timer.

**Comment by facundoq** [comment]
Same here! Latest voice

**Comment by bjohas** [comment]
As far as I can see, this is fixed in 5.0.2 (available as apk from this repo).

**Comment by facundoq** [comment]
Yes, but still an issue on 5.0.1 (latest version on Google Play)

**Comment by PaulWoitaschek** [comment]
Fixed in 5.0.2+
